name: Build FSBL for ANTSDR E200

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-e200:
    runs-on: ubuntu-latest
    env:
      TARGET: e200
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi build-essential dfu-util u-boot-tools device-tree-compiler bc python3 python3-pip cpio zip unzip rsync wget

      - name: Build FSBL for E200
        run: make -C antsdr_e200/sw_apps/zynq_fsbl

      - name: List FSBL artifacts
        run: ls -lh antsdr_e200/sw_apps/zynq_fsbl/*.elf || true

      - name: Upload FSBL artifact
        uses: actions/upload-artifact@v4
        with:
          name: fsbl-elf-e200
          path: antsdr_e200/sw_apps/zynq_fsbl/*.elf
