name: Build FSBL for ANTSDR E200

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-e200:
    runs-on: ubuntu-latest
    env:
      TARGET: e200
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi build-essential dfu-util u-boot-tools device-tree-compiler bc python cpio zip unzip rsync wget

      - name: Setup CROSS_COMPILE
        run: echo "::add-path::$(which arm-linux-gnueabihf-gcc | sed 's:/bin/gcc::')"

      - name: Build firmware
        run: make

      - name: List build artifacts
        run: ls -lh build/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: e200-build
          path: build/*
